version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=commerce
    ports:
      - '5432:5432'

  commerce:
    container_name: ecommerce_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/commerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'